id: P004406
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:50.957289
source_metadata:
  id: bdr:W8LS20418
  title: ལོ་བརྒྱའི་ལོ་ཐོ།
  author: ''
  volumes:
    f651d082e0a44263a960ff788b8bedcf:
      image_group_id: I8LS20420
      title: ''
      volume_number: 1
      total_pages: 651
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
